### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by kugimiya** [free-coders-nutshell/urfc#4]
@ridouchire, have you thought about creating a [Project](https://github.com/free-coders-nutshell/urfc/projects)? Interactive agile-board in Github.

**Comment by Oxore** [comment]
Let me put in my two penny worth. I think it is not the best idea to use something like Kanban or Scrum methodology (Github's "Project" implies this anyway) because of common apathy. This do not make a sense while sometimes everybody has no time to contribute. Just assignation is more than enough, i think.

**Comment by kugimiya** [comment]
rolling on the floor laughing
